package FindTheDifference;

/**
 * You are given two strings s and t.
 * <p>
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * <p>
 * Return the letter that was added to t.
 */
class Solution {
    public char findTheDifference(String s, String t) {
        long answer = 0;
        for (char c : t.toCharArray()) {
            answer += c;
        }
        for (char c : s.toCharArray()) {
            answer -= c;
        }
        return (char)answer;
    }
}